name: Auto PR Bot Manager

on:
  push:
    branches-ignore:
      - main
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  automated:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Ensures the repository is checked out in the workspace

      - name: Run the Automated PR
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.BOT_GH_TOKEN }}
          source_branch: feature-*  # Replace with your actual source branch name
          target_branch: main
          title: Auto PR
          body: "This PR was automated by @npm-run-test."
          reviewer: npm-run-test
          assignee: octocat
          label: enhancement
          draft: false
          old_string: "<!-- UNDEFINED -->"
          new_string: "**Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"
          allow_no_diff: false
