name: Automated PR Manager

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */2 * * *'

jobs:
  create_auto_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: open-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          author: "Hamster [bot] <node_modules@hotmail.com>"
          committer: "Hamster [bot] <node_modules@hotmail.com>"
          signoff: true
          branch: main
          title: 'Automated Pull Request by Actions Bot.'
          body: |
            ## Automated Pull Request by Actions.
            
            > [!IMPORTANT]
            > Trigger / What Happened: ${{ github.event_name }} event at ${{ github.event_path }} path.
            > Details of run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            - Author: @npm-run-test
            - Admin: @offensive-vk
            - Branch: ${{ github.ref }}
            - Commit: ${{ github.sha }}
            - Workflow Path: ${{ github.workflow_ref }}
          labels: |
            bot
            automated
          assignees: npm-run-test
          reviewers: npm-run-test
          draft: false
