name: Automated PR Bot

# run this workflow only on new feature branches, not when they're merged to main
on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Automated PR by @npm-run-test"
          pr_template: ""
          pr_reviewer: "npm-run-test"
          pr_draft: false
