name: Commit Something

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'  # Runs daily at 12:10 AM IST

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create main.txt file
        run: echo "Hello world" > main.txt
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Assign
          commit_user_name: npm-run-test [bot]
          commit_user_email: node_modules@hotmail.com
          branch: ${{ github.ref }}
          commit_options: '-a'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
