name: Updates README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update this repo s README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: Lissy93/github-activity-readme@master
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          COMMIT_MSG: "UPDATED README USING GH ACTIONS"
          MAX_LINES: 10
