run-name: Github Actions by ${{ github.actor }} 

on:
    push:
        branches: ["production", "main"]
    pull_request:
        branches: ["production", "main"]

jobs:
    say_hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Say Hello
              run: echo -e "\t Im saying Hello.\t"
    wish_greetings:
        runs-on: ubuntu-latest
        steps:
            - name: Good morning
              run: echo ${{ github.actor_id }} says Good morning!
            
            - name: Good evening
              run: echo ${{ github.actor }} says Good evening!
    use_env:
        runs-on: ubuntu-latest
        env:
            ACTOR: ${{ github.actor }} with ID ${{ github.actor_id }}.
            KEY: GH Token - ${{ secrets.GITHUB_TOKEN }} and Personal Token - ${{ secrets.BOT_GH_TOKEN }}.
        steps:
            - name: Print Details
              run: echo "$ACTOR"

            - name: Tokens or Secrets
              run: echo "$KEY"

            - name: Remove history
              run: |
                unset $ACTOR ; unset $KEY
                rm -rf ~/.bash_history
                echo "xx Job Finished xx"
    runner-details:
        runs-on: ubuntu-latest
        steps:
          - name: Show details
            run:  |
              echo "Data - ${{ github.event.name }}"
    custom-job:
        runs-on: ubuntu-latest
        steps:
          - name: Fetch the DNS IP
            run: |
              sudo apt update
              sudo apt install speedtest-cli -y
              speedtest --secure
              curl ifconfig.me
