name: Automated Pull Request

on:
  push:
    branches-ignore: [ "main" ]
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  pr_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create PR
        uses: poorva17/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          HEAD_BRANCH: ${{ github.ref_name }}
          BASE_BRANCH: main
