name: 💬 Update Quote Daily

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 UTC everyday
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Quote
        run: |
          # Your command to update the README file goes here
          # For example, to append a quote to the README:
          echo "Added / Updated the Quote."
      - name: Commit changes
        run: |
          git config --local user.email "node_modules@hotmail.com"
          git config --local user.name "npm-run-test [bot]"
          git push
