name: 👩‍💻 Update Recent Activity
on:
  schedule:
    - cron: '0 */4 * * *' # Run every 4 hours
  workflow_dispatch:
jobs:
  update_activity:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Adds activity to readme
        uses: lissy93/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
          COMMIT_MSG: ':zap: Updates recent activity'
        with:
          MAX_LINES: 10

      - name: Adds activity to file
        uses: lissy93/github-activity-readme@master
        permissions:
          contents: write
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
          COMMIT_MSG: ':zap: Updates recent activity'
        with:
          MAX_LINES: 100
          TARGET_FILE: './recent.md'
