name: ☠️ Start all Operations

# Trigger the workflow when a push event occurs on the master branch
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-all-workflows:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the list of workflow files in the .github/workflows directory
      - name: Get workflows
        id: get_workflows
        run: echo ::set-output name=workflows::$(find .github/workflows -name '*.yml' -exec basename {} \;)

      - name: Install Github Cli
        run: |
          sudo apt install gh -y
          sudo apt install github-cli
          
      # Step 2: Run each workflow found in the previous step
      - name: Run each workflow
        run: |
          for workflow in ${{ steps.get_workflows.outputs.workflows }}; do
            echo "Running workflow: $workflow"
            gh workflow run "$workflow" --ref main
          done
