########### SECURE CONTEXT START ##############
name: Uncommit Raw Changes

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0,12 * * *'  # Runs daily at 12:15 AM IST

jobs:
  processing_end:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check for Changes
        run: rm -f main.txt
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Refreshed & Removed Stuff
          commit_user_name: npm-run-test
          commit_user_email: node_modules@hotmail.com
          branch: ${{ github.ref }}
          commit_options: '-a'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}

########### SECURE CONTEXT END ##############
